---
abstract: 'perlbal gateway to MogileFS'
author:
  - 'Victor Igumnov, C<< <victori at fabulously40.com> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Declare: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perlbal-Plugin-MogileFS
no_index:
  directory:
    - inc
    - t
requires:
  Data::Dumper: 0
  MogileFS::Client: 0
  Perlbal: 0
version: undef
