--- 
abstract: ~
author: ~
build_requires: 
  Test::Declare: 0
  Test::More: 0
requires:
  Perlbal: 1.73
  Data::Dumper: 2.125
  MogileFS::Client: 1.09
distribution_type: module
generated_by: Module::Install version 0.680
license: unknown
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Perlbal-Plugin-MogileFS
no_index: 
  directory: 
    - inc
    - t
#requires: 
version: 0.01
